### get para a rota /
GET http://localhost:5000/

### Listar todas os chamados
GET http://localhost:5000/api/chamado/listar

### Cadastrar um novo chamado
POST http://localhost:5000/api/chamado/cadastrar
Content-Type: application/json

{
    "descricao": "Trocar memórias"
}

### Editar um chamado
PUT http://localhost:5000/api/chamado/alterar/d5055d2b-61e7-4d11-9a30-d007ea08ccbf

### Listar chamados não resolvidos
GET http://localhost:5000/api/chamado/naoresolvidos

### Listar chamados resolvidos
GET http://localhost:5000/api/chamado/resolvidos